
@startuml

skinparam ArrowColor #DarkGray
skinparam BorderColor #DarkGray
skinparam BorderThickness 1
skinparam BackgroundColor #LightGray
skinparam ComponentStyle uml2
skinparam Shadowing false

skinparam DefaultFontColor #Black
skinparam DefaultFontName "Roboto"
skinparam DefaultFontStyle normal
skinparam DefaultFontSize 11

@enduml
