
@startuml

skinparam BackgroundColor transparent
skinparam Shadowing false
skinparam ComponentStyle uml2

skinparam Default {
    FontColor #Black
    FontName "Roboto Mono"
    FontStyle normal
    FontSize 11
}

skinparam Class {
    BackgroundColor #LightGray
    BorderColor #DarkGray
    BorderThickness 1
}

@enduml
