@startuml

skinparam ComponentStyle uml2
skinparam Shadowing false

skinparam DefaultFontColor #Black
skinparam DefaultFontName "Arial"
skinparam DefaultFontStyle normal
skinparam DefaultFontSize 11

left to right direction

@enduml
