@startuml

skinparam defaultFontName Arial
skinparam defaultFontSize 11
skinparam defaultFontColor #Black
skinparam componentStyle uml2
skinparam shadowing false
skinparam monochrome true

left to right direction

:User: --> (Show help) 
:User: --> (List timesheet)

@enduml
